# Word2Vec(Gensim)

In [16]:
!pip install gensim

In [ ]:
!git clone https://github.com/songys/Chatbot_data.git
!ls

In [1]:
import gensim
import matplotlib.font_manager as fm
import matplotlib
import matplotlib.pyplot as plt

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('/content/gdrive/Chatbot_data-master/ChatbotData .csv')

In [4]:
all_data = data['Q'].values + data['A'].values

In [5]:
all_text = [sentence.split(' ') for sentence in all_data]

In [6]:
all_text

[['12시', '땡!하루가', '또', '가네요.'],
 ['1지망', '학교', '떨어졌어위로해', '드립니다.'],
 ['3박4일', '놀러가고', '싶다여행은', '언제나', '좋죠.'],
 ['3박4일', '정도', '놀러가고', '싶다여행은', '언제나', '좋죠.'],
 ['PPL', '심하네눈살이', '찌푸려지죠.'],
 ['SD카드', '망가졌어다시', '새로', '사는', '게', '마음', '편해요.'],
 ['SD카드', '안돼다시', '새로', '사는', '게', '마음', '편해요.'],
 ['SNS', '맞팔', '왜', '안하지ㅠㅠ잘', '모르고', '있을', '수도', '있어요.'],
 ['SNS', '시간낭비인', '거', '아는데', '매일', '하는', '중시간을', '정하고', '해보세요.'],
 ['SNS', '시간낭비인데', '자꾸', '보게됨시간을', '정하고', '해보세요.'],
 ['SNS보면', '나만', '빼고', '다', '행복해보여자랑하는', '자리니까요.'],
 ['가끔', '궁금해그', '사람도', '그럴', '거예요.'],
 ['가끔', '뭐하는지', '궁금해그', '사람도', '그럴', '거예요.'],
 ['가끔은', '혼자인게', '좋다혼자를', '즐기세요.'],
 ['가난한', '자의', '설움돈은', '다시', '들어올', '거예요.'],
 ['가만', '있어도', '땀난다땀을', '식혀주세요.'],
 ['가상화폐', '쫄딱', '망함어서', '잊고', '새출발', '하세요.'],
 ['가스불', '켜고', '나갔어빨리', '집에', '돌아가서', '끄고', '나오세요.'],
 ['가스불', '켜놓고', '나온거', '같아빨리', '집에', '돌아가서', '끄고', '나오세요.'],
 ['가스비', '너무', '많이', '나왔다.다음', '달에는', '더', '절약해봐요.'],
 ['가스비', '비싼데', '감기', '걸리겠어따뜻하게', '사세요!'],
 ['가스비', '장난', '아님다음', 

In [7]:
model = gensim.models.Word2Vec(all_text, min_count=1, size=100, window=5)

In [8]:
model.wv.vocab

{'12시': <gensim.models.keyedvectors.Vocab at 0x7fc5a0774358>,
 '땡!하루가': <gensim.models.keyedvectors.Vocab at 0x7fc590adc0f0>,
 '또': <gensim.models.keyedvectors.Vocab at 0x7fc590adc198>,
 '가네요.': <gensim.models.keyedvectors.Vocab at 0x7fc590adc1d0>,
 '1지망': <gensim.models.keyedvectors.Vocab at 0x7fc590adc208>,
 '학교': <gensim.models.keyedvectors.Vocab at 0x7fc590adc240>,
 '떨어졌어위로해': <gensim.models.keyedvectors.Vocab at 0x7fc590adc278>,
 '드립니다.': <gensim.models.keyedvectors.Vocab at 0x7fc590adc2b0>,
 '3박4일': <gensim.models.keyedvectors.Vocab at 0x7fc590adc2e8>,
 '놀러가고': <gensim.models.keyedvectors.Vocab at 0x7fc590adc320>,
 '싶다여행은': <gensim.models.keyedvectors.Vocab at 0x7fc590adc358>,
 '언제나': <gensim.models.keyedvectors.Vocab at 0x7fc590adc390>,
 '좋죠.': <gensim.models.keyedvectors.Vocab at 0x7fc590adc3c8>,
 '정도': <gensim.models.keyedvectors.Vocab at 0x7fc590adc400>,
 'PPL': <gensim.models.keyedvectors.Vocab at 0x7fc590adc438>,
 '심하네눈살이': <gensim.models.keyedvectors.Vocab at 0x7fc590adc47

In [9]:
model.init_sims(replace=True)

In [10]:
model.wv.most_similar('SNS')

[('몰려가는', 0.42272353172302246),
 ('사세요.', 0.4178297519683838),
 ('만나고', 0.38810479640960693),
 ('필요해요.', 0.38447409868240356),
 ('짝남이', 0.37634190917015076),
 ('같았나봅니다.', 0.36504876613616943),
 ('괜히', 0.3638080358505249),
 ('사람일지도', 0.35942453145980835),
 ('가야겠다.다양하게', 0.3518522381782532),
 ('사람이', 0.3510091006755829)]

In [11]:
model.wv.most_similar('왜')

[('안', 0.9690231084823608),
 ('더', 0.9667078256607056),
 ('좀', 0.9649061560630798),
 ('다', 0.963874101638794),
 ('너무', 0.9590301513671875),
 ('내', 0.9582716822624207),
 ('다시', 0.9580177068710327),
 ('건', 0.9565128087997437),
 ('잘', 0.9559733867645264),
 ('어떻게', 0.9551650881767273)]

In [12]:
model.wv.most_similar('다이어트')

[('만나면', 0.4131609797477722),
 ('맛있어요.', 0.39602017402648926),
 ('카톡차단에', 0.3959500789642334),
 ('기르고', 0.37677526473999023),
 ('적극적이지가', 0.3720919191837311),
 ('뭐냐그래도', 0.3671272397041321),
 ('헤어졌습니다긴', 0.3652966022491455),
 ('좋아할까?마다할', 0.36184611916542053),
 ('가까워지고', 0.34875431656837463),
 ('애정이', 0.3476570248603821)]

In [13]:
print(model.wv.vectors)

[[-0.02146148 -0.06629257 -0.0571418  ...  0.05809021  0.0426666
   0.04949467]
 [-0.00085892 -0.06711042 -0.03391437 ...  0.02549057  0.02885363
   0.03118342]
 [ 0.00553412 -0.08703209 -0.04306027 ...  0.06753093 -0.01427031
   0.06784515]
 ...
 [ 0.15578975 -0.08788785  0.00428558 ... -0.0542782   0.12758602
  -0.00542788]
 [-0.14061755 -0.04675566 -0.00043559 ... -0.05196697 -0.10355247
  -0.07373328]
 [-0.05049521  0.07852653  0.0203968  ...  0.01223052 -0.11582281
  -0.08928913]]


In [14]:
print(model.wv.vectors.shape)

(26001, 100)


## initalize embedding matrix by pretrained weight

In [ ]:
!pip install -q tensorflow-gpu==2.0.0-rc1

In [1]:
samples = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 좋은 일이 생겼어',
          '아 오늘 진짜 짜증나',
          '환상적인데, 정말 좋은거 같아']

targets =[[1], [0], [1], [1], [0], [1]]

In [2]:
import os
import tensorflow as tf
import numpy as np

from tensorflow.keras import preprocessing

In [3]:
tokenizer = preprocessing.text.Tokenizer() 
tokenizer.fit_on_texts(samples) 
sequences = tokenizer.texts_to_sequences(samples)
input_sequences = preprocessing.sequence.pad_sequences(sequences, maxlen = 6, padding='post')

labels = np.array(targets)

word_index = tokenizer.word_index

print(f"index text data : \n{input_sequences}\n")
print(f"shape of sequences:{input_sequences.shape}")
print(f"shape of labels:{labels.shape}")

index text data : 
[[ 4  1  5  6  0  0]
 [ 7  1  8  9  0  0]
 [10  2  3 11  0  0]
 [12  2  3 13  0  0]
 [14  1 15 16  0  0]
 [17 18 19 20  0  0]]

shape of sequences:(6, 6)
shape of labels:(6, 1)


In [4]:
from tensorflow.keras import backend
from tensorflow.keras import layers
batch_size = 2
num_epochs = 100
vocab_size = len(word_index) + 1
emb_size = 128
hidden_dimension = 256
output_dimension = 1

In [49]:
class Model(tf.keras.Model):

    def __init__(self, vocab_size, embed_dimension, hidden_dimension, output_dimension, embedding_weight=None):
        super(Model, self).__init__(name='my_model')
        self.embedding = layers.Embedding(vocab_size, embed_dimension, weights=[embedding_weight])
        self.dense_layer = layers.Dense(hidden_dimension, activation='relu')
        self.output_layer = layers.Dense(output_dimension, activation='sigmoid')

    def call(self, inputs):
        x = self.embedding(inputs)
        x = tf.reduce_mean(x, axis=1)
        x = self.dense_layer(x)
        x = self.output_layer(x)
        
        return x

In [50]:
model = Model(vocab_size = vocab_size,
            embed_dimension=emb_size,
            hidden_dimension=hidden_dimension,
            output_dimension=output_dimension,
            embedding_weight=model.wv.vectors)

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Train on 6 samples
Epoch 1/100
6/6 [==============================] - 0s 48ms/sample - loss: 0.5873 - accuracy: 0.8333
Epoch 2/100
6/6 [==============================] - 0s 916us/sample - loss: 0.4210 - accuracy: 0.8333
Epoch 3/100
6/6 [==============================] - 0s 869us/sample - loss: 0.2847 - accuracy: 1.0000
Epoch 4/100
6/6 [==============================] - 0s 932us/sample - loss: 0.2221 - accuracy: 1.0000
Epoch 5/100
6/6 [==============================] - 0s 920us/sample - loss: 0.1681 - accuracy: 1.0000
Epoch 6/100
6/6 [==============================] - 0s 907us/sample - loss: 0.1337 - accuracy: 1.0000
Epoch 7/100
6/6 [==============================] - 0s 947us/sample - loss: 0.1049 - accuracy: 1.0000
Epoch 8/100
6/6 [==============================] - 0s 816us/sample - loss: 0.0805 - accuracy: 1.0000
Epoch 9/100
6/6 [==============================] - 0s 819us/sample - loss: 0.0645 - accuracy: 1.0000
Epoch 10/100
6/6 [==============================] - 0s 1ms/sample - loss:

Epoch 82/100
6/6 [==============================] - 0s 1ms/sample - loss: 8.0392e-04 - accuracy: 1.0000
Epoch 83/100
6/6 [==============================] - 0s 949us/sample - loss: 7.7857e-04 - accuracy: 1.0000
Epoch 84/100
6/6 [==============================] - 0s 934us/sample - loss: 7.5537e-04 - accuracy: 1.0000
Epoch 85/100
6/6 [==============================] - 0s 1ms/sample - loss: 7.3235e-04 - accuracy: 1.0000
Epoch 86/100
6/6 [==============================] - 0s 1ms/sample - loss: 7.1114e-04 - accuracy: 1.0000
Epoch 87/100
6/6 [==============================] - 0s 929us/sample - loss: 6.9187e-04 - accuracy: 1.0000
Epoch 88/100
6/6 [==============================] - 0s 1ms/sample - loss: 6.7150e-04 - accuracy: 1.0000
Epoch 89/100
6/6 [==============================] - 0s 863us/sample - loss: 6.5351e-04 - accuracy: 1.0000
Epoch 90/100
6/6 [==============================] - 0s 803us/sample - loss: 6.3714e-04 - accuracy: 1.0000
Epoch 91/100
6/6 [==============================] - 0s